name: CI/CD for Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted  # Use self-hosted runner for local access
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify Python version
        run: python3 --version
        
      - name: Install dependencies
        run: pip install -r requirements.txt --break-system-packages

      - name: Lint with flake8
        run: flake8 dags/ --count --show-source --statistics

      #- name: Check formatting with black
        #run: black --check dags/

  test:
    runs-on: self-hosted
    needs: lint  # Run after lint succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Python version
        run: python3 --version
 
      - name: Install dependencies
        run: pip install -r requirements.txt --break-system-packages

      - name: Run tests
        run: pytest test/  # Validates DAG structure and ELT functions

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Minikube is running
        run: minikube status || minikube start

      - name: Deploy DAG to Airflow in Minikube
        run: |
          # Verify namespace exists
          kubectl get namespace elt-pipeline || kubectl create namespace elt-pipeline
          # Get Airflow scheduler pod name with error handling
          # POD_NAME=$(kubectl get pods -n elt-pipeline -l app=airflow,component=scheduler -o jsonpath="{.items[0].metadata.name}" || echo "")
          POD_NAME=$(kubectl get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep airflow-scheduler)
          if [ -z "$POD_NAME" ]; then
            echo "Error: No Airflow in namespace elt-pipeline"
            exit 1
          fi
          DAG_FOLDER=/opt/airflow/dags
          kubectl cp dags/elt_dag.py $POD_NAME:$DAG_FOLDER/elt_dag.py -n elt-pipeline
          kubectl exec -n elt-pipeline $POD_NAME -- airflow dags reserialize


      - name: Verify Deployment
        run: |
          kubectl get namespace elt-pipeline || { echo "Namespace elt-pipeline not found"; exit 1; }
          kubectl get svc airflow-api-server -n elt-pipeline || { echo "Service airflow-api-server not found"; exit 1; }
          kubectl port-forward svc/airflow-api-server 8080:8080 -n elt-pipeline &
          PORT_FORWARD_PID=$!
          sleep 10
          # Retry curl command up to 5 times with a 5-second delay
          for i in {1..5}; do
            if curl -s -H "Authorization: Bearer ${{ secrets.AIRFLOW_TOKEN }}" http://localhost:8080/api/v2/dags | grep "elt_sales_pipeline"; then
              echo "DAG elt_sales_pipeline found in API response"
              break
            else
              echo "Attempt $i: Failed to find DAG in API response"
              sleep 5
              if [ $i -eq 5 ]; then
                echo "Error: Failed to verify elt_sales_pipeline after 5 attempts"
                kill $PORT_FORWARD_PID
                exit 1
              fi
            fi
          done
          kill $PORT_FORWARD_PID    
