name: CI/CD for Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted  # Use self-hosted runner for local access
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify Python version
        run: python3 --version
        
      - name: Install dependencies
        run: pip install -r requirements.txt --break-system-packages

      - name: Lint with flake8
        run: flake8 dags/ --count --show-source --statistics

      #- name: Check formatting with black
        #run: black --check dags/

  test:
    runs-on: self-hosted
    needs: lint  # Run after lint succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Python version
        run: python3 --version
 
      - name: Install dependencies
        run: pip install -r requirements.txt --break-system-packages

      - name: Run tests
        run: pytest test/  # Validates DAG structure and ELT functions

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Minikube is running
        run: minikube status || minikube start

      - name: Deploy DAG to Airflow in Minikube
        run: |
          # Verify namespace exists
          kubectl get namespace elt-pipeline || kubectl create namespace elt-pipeline
          # Get Airflow pod name with error handling
          POD_NAME=$(kubectl get pods -n elt-pipeline -l app.kubernetes.io/name=elt-pipeline -o jsonpath="{.items[0].metadata.name}" || echo "")
          if [ -z "$POD_NAME" ]; then
            echo "Error: No Airflow pods found with label app.kubernetes.io/name=elt-pipeline in namespace elt-pipeline"
            exit 1
          fi
          DAG_FOLDER=/opt/airflow/dags
          kubectl cp dags/elt_dag.py $POD_NAME:$DAG_FOLDER/elt_dag.py -n elt-pipeline
          kubectl exec -n elt-pipeline $POD_NAME -- airflow dags reserialize

      - name: Verify Deployment
        run: |
          kubectl port-forward svc/airflow-api-server 8080:8080 -n elt-pipeline &
          sleep 5
          curl -s http://localhost:8080/api/v1/dags | grep "elt_pipeline"
